services:
  keuangan-bumantara:
    image: nginx:alpine
    container_name: keuangan-bumantara
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
